/* src/components/ScoreDashboard/ScoreDashboard.jsx */
import React, { useState } from 'react';
import { Award, ChevronDown, ChevronUp, Download, RotateCcw, ThumbsUp, AlertTriangle, Lightbulb } from 'lucide-react';
import './ScoreDashboard.css';

export default function ScoreDashboard({ results, interviewConfig, onRestart }) {
  const { domain, difficulty, interviewerName } = interviewConfig;
  const [expandedIndex, setExpandedIndex] = useState(0);

  // Calculate Average Score
  const totalScore = results.reduce((acc, curr) => acc + curr.score, 0);
  const averageScore = results.length > 0 ? Math.round((totalScore / results.length) * 10) / 10 : 0;

  // Rating details
  const getRatingInfo = () => {
    if (averageScore >= 8.5) {
      return {
        label: 'Distinguished',
        desc: 'Exceptional performance. You demonstrated a deep understanding of core concepts, excellent terminology, and solid problem-solving approaches.',
        class: 'excellent',
        color: '#10b981'
      };
    } else if (averageScore >= 7.0) {
      return {
        label: 'Proficient',
        desc: 'Strong performance. You possess a good understanding of the domain, though minor technical details or completeness could be improved.',
        class: 'good',
        color: '#38bdf8'
      };
    } else if (averageScore >= 5.0) {
      return {
        label: 'Competent',
        desc: 'Passing performance. You understand basic workflows, but need to study conceptual specifics, edge cases, and terminology details.',
        class: 'avg',
        color: '#f59e0b'
      };
    } else {
      return {
        label: 'Needs Development',
        desc: 'Further study recommended. Focus on core syntax, system design patterns, and foundational concepts in this domain.',
        class: 'bad',
        color: '#f43f5e'
      };
    }
  };

  const rating = getRatingInfo();

  // SVG Circle Constants for Radial Progress
  const radius = 60;
  const stroke = 8;
  const normalizedRadius = radius - stroke * 2;
  const circumference = normalizedRadius * 2 * Math.PI;
  const strokeDashoffset = circumference - (averageScore / 10) * circumference;

  // Export Interview Report File
  const handleDownloadReport = () => {
    let reportText = `==================================================\n`;
    reportText += `       INTERVAI TECHNICAL ASSESSMENT REPORT        \n`;
    reportText += `==================================================\n\n`;
    reportText += `Candidate Profile:\n`;
    reportText += `- Tech Domain: ${domain}\n`;
    reportText += `- Difficulty Level: ${difficulty}\n`;
    reportText += `- Interviewer: ${interviewerName}\n`;
    reportText += `- Overall Grade: ${averageScore} / 10 (${rating.label})\n\n`;
    reportText += `Assessed Performance Summary:\n`;
    reportText += `${rating.desc}\n\n`;
    reportText += `==================================================\n`;
    reportText += `            QUESTION-BY-QUESTION BREAKDOWN        \n`;
    reportText += `==================================================\n\n`;

    results.forEach((res, i) => {
      reportText += `Q${i + 1}: ${res.question}\n`;
      reportText += `Candidate Score: ${res.score} / 10\n`;
      reportText += `Candidate Answer:\n"${res.answer}"\n`;
      reportText += `Feedback:\n${res.feedback}\n`;
      reportText += `Model Answer Reference:\n${res.sampleAnswer}\n`;
      reportText += `--------------------------------------------------\n\n`;
    });

    reportText += `Assessment generated by IntervAI on ${new Date().toLocaleDateString()}.\n`;

    // Download Logic
    const element = document.createElement("a");
    const file = new Blob([reportText], { type: 'text/plain' });
    element.href = URL.createObjectURL(file);
    element.download = `IntervAI_Assessment_${domain.replace(" ", "_")}.txt`;
    document.body.appendChild(element);
    element.click();
    document.body.removeChild(element);
  };

  const toggleExpand = (index) => {
    setExpandedIndex(expandedIndex === index ? -1 : index);
  };

  return (
    <div className="dashboard-container animate-fade-in">
      {/* Top summary panel */}
      <div className="summary-banner glass-panel">
        <div className="radial-score-box">
          <svg className="radial-svg" height={radius * 2} width={radius * 2}>
            {/* Background track */}
            <circle
              className="radial-circle-track"
              stroke="rgba(255,255,255,0.03)"
              fill="transparent"
              strokeWidth={stroke}
              r={normalizedRadius}
              cx={radius}
              cy={radius}
            />
            {/* Score fill */}
            <circle
              className={`radial-circle-fill ${rating.class}`}
              stroke={rating.color}
              fill="transparent"
              strokeWidth={stroke}
              strokeDasharray={circumference + ' ' + circumference}
              style={{ strokeDashoffset }}
              r={normalizedRadius}
              cx={radius}
              cy={radius}
            />
          </svg>
          <div className="score-display">
            <span className="score-num">{averageScore}</span>
            <span className="score-total">/10</span>
          </div>
        </div>

        <div className="summary-text-section">
          <div className="summary-heading-row">
            <h1 className="summary-title">Interview Summary</h1>
            <span className={`rating-badge ${rating.class}`}>{rating.label}</span>
          </div>
          <p className="summary-desc">{rating.desc}</p>
          <div className="meta-info-row">
            <span>Domain: <strong>{domain}</strong></span>
            <span className="separator">•</span>
            <span>Target Level: <strong>{difficulty}</strong></span>
            <span className="separator">•</span>
            <span>Questions: <strong>{results.length}</strong></span>
          </div>
        </div>

        <div className="dashboard-action-buttons">
          <button className="download-btn" onClick={handleDownloadReport}>
            <Download size={16} />
            <span>Download Report</span>
          </button>
          
          <button className="restart-btn-dash" onClick={onRestart}>
            <RotateCcw size={16} />
            <span>New Interview</span>
          </button>
        </div>
      </div>

      {/* Breakdown list */}
      <div className="breakdown-list-section">
        <h2 className="breakdown-title">
          <Award size={18} className="breakdown-title-icon" />
          Detailed Performance Breakdown
        </h2>

        <div className="questions-grid">
          {results.map((res, index) => {
            const isExpanded = expandedIndex === index;
            return (
              <div 
                key={index} 
                className={`breakdown-card glass-panel ${isExpanded ? 'expanded' : ''}`}
              >
                <div 
                  className="breakdown-card-header" 
                  onClick={() => toggleExpand(index)}
                >
                  <div className="header-left">
                    <span className="q-badge">Question {index + 1}</span>
                    <span className="q-preview">{res.question}</span>
                  </div>
                  <div className="header-right">
                    <span className={`score-label ${res.score >= 8 ? 'good' : res.score >= 5 ? 'avg' : 'bad'}`}>
                      {res.score}/10
                    </span>
                    {isExpanded ? <ChevronUp size={16} /> : <ChevronDown size={16} />}
                  </div>
                </div>

                {isExpanded && (
                  <div className="breakdown-card-body">
                    {/* User Answer */}
                    <div className="body-block">
                      <div className="block-label"><ThumbsUp size={13} /> Your Answer</div>
                      <p className="block-text candidate-answer-text">"{res.answer}"</p>
                    </div>

                    {/* Feedback */}
                    <div className="body-block">
                      <div className="block-label"><AlertTriangle size={13} /> Evaluation Feedback</div>
                      <p className="block-text feedback-text">{res.feedback}</p>
                    </div>

                    {/* Sample Answer */}
                    <div className="body-block">
                      <div className="block-label"><Lightbulb size={13} /> Model Answer Reference</div>
                      <p className="block-text model-answer-text">{res.sampleAnswer}</p>
                    </div>
                  </div>
                )}
              </div>
            );
          })}
        </div>
      </div>
    </div>
  );
}
